#169817863 user account activation and email verification
andela/blackninjas-backend pull request #17
Opened 2019-12-09 18:33 UTC by shemaeric1234

### What does this PR do?
An email should be sent to a user upon successful registration  and should be able to receive a verification link via email upon successful signup
### Description of Task to be completed?
- The user after sign-up he or she should receive an email a which includes a verification link
- User should activate his or her account by clicking on the verification link

### How should this be manually tested?
After clone repository goes to the root of the project open path into command run the npm install and once setup is done click npm test.

Using Postman to test all endpoints:
Key: Content-Type value: application/JSON
To test authentication, add this to the header: Bearer TOKEN
Test endpoints
PATCH request
visit: URL API/v2/activate/id

### What are the relevant pivotal tracker stories?
[#169817863](https://www.pivotaltracker.com/story/show/169817863)

### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/47531860/70461915-7361fa80-1ac2-11ea-9bfd-75cbaec84c8f.png)
![image](https://user-images.githubusercontent.com/47531860/70462022-aefcc480-1ac2-11ea-9fdd-653ad3c5daf7.png)

2019-12-10 17:49 UTC, aanchirinah requested changes
Good job just kindly attend to my requests.

2019-12-10 17:49 UTC, aanchirinah commented on src/controllers/Users.js
> +   * @param {int} req
### Nitpick
- Add a descriptive JS Doc

2019-12-10 17:49 UTC, aanchirinah commented on src/database/migrations/20191205184718-create-users.js
> +    active: {
### Nitpick

- Give a default value for this.

2019-12-10 17:49 UTC, aanchirinah commented on src/helpers/sendEmail.js
> + * @param {string} to
### Nitpick
- Descriptive JS Doc.

2019-12-10 17:49 UTC, aanchirinah commented on src/middlewares/verifyToken.js
> +  const token = req.headers.authorization.split(' ')[1];
### Nitpick

- You may want to check if it's a `Bearer` token also.

2019-12-10 17:49 UTC, aanchirinah commented on src/services/users/servises.js
> +    const userToUpdate = await database.users.findOne({
### Nitpick

- You need to perform some sort of exception handling also.

2019-12-10 17:49 UTC, aanchirinah commented on src/tests/users.js
> +  it('it should check if user accoutn is activated', (done) => {
```suggestion
  it('it should check if user account is activated', (done) => {
```

2019-12-11 05:35 UTC, shemaeric1234 commented on src/tests/users.js
> +  it('it should check if user accoutn is activated', (done) => {
I have done

2019-12-11 08:47 UTC, jo-rdan approved these changes
Eric good job so far!

2019-12-13 09:58 UTC, shemaeric1234 commented
I have completed the feedback , so you can review

2019-12-16 14:31 UTC, aanchirinah approved these changes

2019-12-16 14:38 UTC, Jajabenit250 approved these changes

2019-12-17 01:00 UTC, merged