#169817865 User Should Sign In with Email and Password
andela/blackninjas-backend pull request #19
Opened 2019-12-10 17:09 UTC by Jajabenit250

#### What does this PR do?
- User Should SignIn with Email and Password
#### Description of Task to be completed?
- Functionality of User SignIn with Email and Password
- Validating Input (email and Password)
- Checking In Database the combination of Email and Password
- Tests of User Should Login With Email and Password
- Swagger Documentation Of user should login With Password
#### How should this be manually tested?
- Clone the repo and run Npm test
#### Any background context you want to provide?
- N/A
#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/169817865
#### Screenshots (if appropriate) 
<img width="1440" alt="Screen Shot 2019-12-09 at 19 10 58" src="https://user-images.githubusercontent.com/51251401/70456900-c3878f80-1ab7-11ea-883c-ebfc31254247.png">

#### Questions:

2019-12-10 19:26 UTC, aanchirinah requested changes
Great work please attend to the changes requested

2019-12-10 19:26 UTC, aanchirinah commented on src/app.js
>  app.use('/API/v1', swagger);
### Nitpick

- Maintain consistency with string casing, preferably should be of the lower case.

2019-12-10 19:26 UTC, aanchirinah commented on src/controllers/userController.js
> +      checkEmailpassword(req, res);
### Nitpick

- I see `Async` but no `Await` block of code being used.

2019-12-10 19:26 UTC, aanchirinah commented on src/controllers/userController.js
> +        req,
### Nitpick

- Handle error messages in this format
```
- Error code
- Message
- Data
- StatusCode
```

2019-12-10 19:26 UTC, aanchirinah commented on src/database/models/user.js
> +    firstName: DataTypes.STRING,
### Nitpick

- Add `allowNull` property

2019-12-11 17:56 UTC, jo-rdan approved these changes
Good job Benit, keep it up!

2019-12-13 07:19 UTC, Jajabenit250 commented
@aanchirinah All change requested are resolved

2019-12-17 14:49 UTC, aanchirinah approved these changes

2019-12-17 14:53 UTC, shemaeric1234 approved these changes

2019-12-17 17:07 UTC, merged