#169817876 User requests Table
andela/blackninjas-backend pull request #28
Opened 2019-12-31 13:50 UTC by Jajabenit250

#### What does this PR do?
- User can View all requests he/she submitted to barefoot Nomad
#### Description of Task to be completed?
- User will click to my requests button under dropdown menu
- Check if user is loggedIN
- return to the user the Requests Data
#### How should this be manually tested?
-  Clone this repository
-  git checkout feature/169817876/user-table-of-requests
-  open console and type and run(- npm install) to install all dependencies
-  and then run (- npm start) to start the server
#### Any background context you want to provide?
- User need to be logged in before viewing his/her requests made
#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/169817876
#### Screenshots (if appropriate) 

#### Questions:

2020-01-03 15:04 UTC, mujohn26 approved these changes

2020-01-06 15:52 UTC, bdushimi requested changes

2020-01-06 15:52 UTC, bdushimi commented on src/controllers/trips.controller.js
> +  static async returnTripController(req, res) {
Hey @Jajabenit250, the function should not have -controller suffix in their names. Besides the function is inside a controller, is there a reason to add -controller to the name?

2020-01-06 15:52 UTC, bdushimi commented on src/controllers/trips.controller.js
> +      const userManager = await tripsService.findUserManager(createdTrip.userId);
Hey @Jajabenit250, for the sake of separating concerns, tripService should not deal with user management. There's a need for another service that should cater for that

2020-01-10 08:36 UTC, bdushimi requested changes

2020-01-10 08:36 UTC, bdushimi commented on src/routes/trip.route.js
> +router.get('/myrequests', verifyToken.headerToken, verifyUser, tripController.getTripRequestsByUser);
Hey @Jajabenit250 wouldn't it be much better to name this route as */users/:userID/trip-requests*?.

2020-01-10 09:48 UTC, merged