feat(notification):manager get notification
andela/blackninjas-backend pull request #45
Opened 2020-01-16 20:04 UTC by mujohn26

#### What does this PR do?

This PR adds notification functionality.
When the requester edit a trip a  notification will be sent to the manager for both in-app and via email.
#### Description of Task to be completed?

* There may be 2 types of notifications: email notifications and in-app notifications.
* Email notifications are sent as email messages to the email address the user submitted during registration.
* Users should be able to opt out (and in) of this type of notification.
* In-app notifications show up in the app. This may be visible on a notification page or some other view, as the team may choose.
#### How should this be manually tested?

- After clone repository, go to the root of the project open path into command run the `npm install` and once setup is done click `npm test`.

- In Postman, create a GET request with this url:`localhost:3000/api/v1/notifications` and pass `token` in headers
#### Screenshots

<img width="1288" alt="Screen Shot 2020-01-16 at 22 02 15" src="https://user-images.githubusercontent.com/52497006/72558779-11a86380-38ac-11ea-9477-f82204c95caf.png">

#### What are the relevant pivotal tracker stories?
[#169817894](https://www.pivotaltracker.com/story/show/169817894)

2020-01-17 13:40 UTC, VedaDom approved these changes

2020-01-17 15:41 UTC, jo-rdan commented on src/controllers/user.controller.js
>      if (updaUser.status === 200) {
@mujohn26 , this variable seems to be misspelled, kindly update this to a more intuitive name

2020-01-17 15:49 UTC, jo-rdan requested changes
Good job so far @mujohn26, one little thing to change and I am ok!

2020-01-20 12:09 UTC, bdushimi requested changes

2020-01-20 12:09 UTC, bdushimi commented on src/controllers/trip.controller.js
>        await NotificationService.sendNotification('trip_request_event', managerId, `New ${type} trip request.`, `${req.user.firstName} has requested a new ${type}`, tripRequest.id, 'http://localhost:3
@mujohn26 Kindly use the environment variable to point to a particular URL depending on the application environment

2020-01-20 12:09 UTC, bdushimi commented on src/controllers/trip.controller.js
> +
@mujohn26 This PR is introducing changes that are not relevant to its purpose. The PR contains codes related to updating trips and trip-requests yet this PR is supposed to contain codes that send notifications to a requester's manager. I think you branched out of edit-trip-request branch. Before you start off a new feature, always branch out from develop.

2020-01-21 14:52 UTC, merged