feat(stats): User should be able to get statistics of trips made in a…
andela/blackninjas-backend pull request #50
Opened 2020-01-21 12:22 UTC by jo-rdan

#### What does this PR do?
A user should be able to get detailed statistics in terms of number of trips he/she created in the last X timeframe
#### Description of Task to be completed?
- Implement functionality for this feature
- query to get trips made by the user logged in
#### How should this be manually tested?
- clone this repo to your local pc
- make sure all the packages are installed by typing `npm install`
- make sure you have all migrations by typing `npm run db-migrate`
- in postman use this route to access the endpoint `/api/v1/trip/trip-statistics` add the token of the user in the headers and hit send you should get the total number of trips and a breakdown of trips a user created by the trip type
#### Any background context you want to provide?
- The user has to be logged in
#### What are the relevant pivotal tracker stories?
[#169817900](https://www.pivotaltracker.com/story/show/169817900)
#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/51836855/72804520-35c3c600-3c59-11ea-87da-17705f89cc57.png)

2020-01-22 15:21 UTC, VedaDom approved these changes

2020-01-22 15:47 UTC, mujohn26 approved these changes

2020-01-22 20:53 UTC, bdushimi requested changes

2020-01-22 20:53 UTC, bdushimi commented on src/controllers/trip.controller.js
> +      'approve-or-reject-trip_request_event',
@jo-rdan May you remove this white space?

2020-01-22 20:53 UTC, bdushimi commented on src/controllers/trip.controller.js
> +      details.map((detailedTrip) => {
@jo-rdan The correct array function to use here is reduce(), instead of using map().

2020-01-22 20:53 UTC, bdushimi commented on src/tests/0000ztrips.js
> +        res.should.have.status(200);
@jo-rdan You need not only to assert the response status but also the returned data. Test if the correct data are returned.

2020-01-23 08:34 UTC, bdushimi approved these changes

2020-01-23 08:35 UTC, merged