#169817889 send and receive comment notification
andela/blackninjas-backend pull request #51
Opened 2020-01-21 13:41 UTC by shemaeric1234

### What does this PR do?

This PR will help a user to receive notifications for posted comments

### Description of Task to be completed?

As a requester, I should be able to see notifications when comments are posted on my request
So that  I can determine the next line of action

### How should this be manually tested?
After clone repository goes to the root of the project open path into command run the npm install and once setup is done click npm test.

Using Postman to test endpoints:
after sign in you will get a token
Then
Key: Content-Type value: application/JSON
To test authentication, add this to the header: Bearer <TOKEN>

using POST request
visit: URL 1.  localhost:3000/api/v1/trip-requests/{commentID}/comments

#### Any background context you want to provide?

Only for someone who has an account

#### Screenshots (if appropriate)
[#169817889](https://www.pivotaltracker.com/story/show/169817889)
#### Questions:

2020-01-22 16:11 UTC, jo-rdan requested changes
@shemaeric1234 , good job so far my friend! check the comment below and we should be good to go

2020-01-22 16:11 UTC, jo-rdan commented on src/controllers/trip.controller.js
> +    await NotificationService.sendNotification('trip_request_comment_event', receiver, 'New Comment', `${req.user.firstName} has posted a new comment`, data.dataValues.id, 'http://localhost:3000/api/
@shemaeric1234 , on this function, you should use the base url for us to be able to access it on the production link

2020-01-22 20:03 UTC, bdushimi requested changes

2020-01-22 20:03 UTC, bdushimi commented on src/tests/comment.test.js
> +  it('comment should successfuly be created buy a requester', (done) => {
@shemaeric1234 By instead of Buy

2020-01-22 20:03 UTC, bdushimi commented on src/tests/comment.test.js
> +  it('comment should successfuly be created buy a manager', (done) => {
@shemaeric1234 By instead of Buy

2020-01-22 20:03 UTC, bdushimi commented on src/tests/comment.test.js
>    it('should display an error message in case a trip request does not have a comment', (done) => {
Just because a trip-request does not have a comment, it does not mean that there has been an error. If you were testing here a get operation, the expected data message object should be empty

2020-01-22 20:03 UTC, bdushimi commented on src/controllers/trip.controller.js
> +    await NotificationService.sendNotification('trip_request_comment_event', receiver, 'New Comment', `${req.user.firstName} has posted a new comment`, data.dataValues.id, `${process.env.BASE_URL}/ap
@shemaeric1234 I guess you're sending email notification too? what will happen if the user clicks view message from the inbox?

2020-01-23 11:57 UTC, mujohn26 approved these changes

2020-01-27 10:53 UTC, bdushimi approved these changes

2020-01-27 10:53 UTC, merged